<template>
  <main class="shell">
    <aside><div class="brand"><span class="brand-mark">◌</span><div><b>Disk Sense</b><small>空间记忆系统</small></div></div><nav><button :class="{active:view==='overview'}" @click="view='overview'">空间总览</button><button :class="{active:view==='cleaner'}" @click="view='cleaner'">常规清理</button><button :class="{active:view==='memory'}" @click="view='memory'">个人空间</button><button :class="{active:view==='growth'}" @click="view='growth'">增长趋势</button></nav><div class="aside-foot">新架构 · 只读原型<br><span>所有结论都显示证据</span></div></aside>
    <section class="content" v-if="view==='cleaner'"><CleanerPanel /></section><section class="content" v-else-if="view==='memory'"><header><div><p class="kicker">PERSONAL SPACE</p><h1>个人空间</h1><p class="subtitle">查看长期未使用、来源不明和用户自己决定保留的内容。</p></div><button class="scan" @click="runScan">重新分析</button></header><div class="personal-list"><div v-for="source in sources.filter(x=>x.classification==='personal'||x.classification==='stale')" :key="source.id" class="source"><div class="source-dot"></div><div class="source-info"><b>{{ source.title }}</b><span>{{ source.count }} 个对象</span></div><strong>{{ format(source.bytes) }}</strong></div><p v-if="!sources.length" class="muted">先进行一次空间体检。</p></div></section><section class="content" v-else-if="view==='growth'"><header><div><p class="kicker">GROWTH TRACKING</p><h1>增长趋势</h1><p class="subtitle">每次扫描都会留下快照，用来识别会反复回来的空间。</p></div><button class="scan" @click="runScan">建立新快照</button></header><div class="trend-card"><b>{{ events.length ? '已发现变化' : '等待第二次快照' }}</b><p>{{ events.length ? `最近记录了 ${events.length} 条文件变化。` : '第一次扫描只能建立基线，第二次扫描后才能计算增长。' }}</p></div><div v-for="event in events" :key="event.path + event.observedAt" class="event"><span class="event-kind">{{ event.kind }}</span><div><b>{{ event.path }}</b><small>{{ event.observedAt }}</small></div></div></section><section class="content" v-else><header><div><p class="kicker">STORAGE OBSERVABILITY</p><h1>你的空间正在发生什么</h1><p class="subtitle">清理只是一次动作，理解增长来源才能让空间真正稳定下来。</p></div><div class="head-actions"><button class="quiet" @click="showAgent=true">Agent 上下文</button><button class="scan" @click="runScan">{{ scanning ? '分析中…' : '开始空间体检' }}</button></div></header>
      <div class="notice"><span>◷</span><div><b>这次是只读分析</b><p>不会修改或删除任何文件。先建立第一张空间快照，再决定下一步。</p></div></div>
      <div class="cards"><article><span>当前状态</span><strong>{{ scanning ? '正在建立快照' : '等待首次体检' }}</strong><small>{{ scanning ? '读取文件元数据和目录关系' : '建议先扫描用户目录和应用数据' }}</small></article><article><span>产品原则</span><strong>未知 ≠ 垃圾</strong><small>无法判断的内容会保留给你决定</small></article><article><span>长期目标</span><strong>找到反复增长</strong><small>比较多次快照，而不是只清理一次</small></article></div>
      <section class="empty" v-if="!scanned"><div class="empty-orbit">◌</div><h2>先建立你的空间地图</h2><p>Disk Sense 会从文件、应用、时间和路径关系开始理解这台电脑。</p><button class="scan secondary" @click="runScan">建立第一张快照</button></section>
      <section v-else class="result"><h2>空间来源</h2><div v-for="source in sources" :key="source.id" class="source"><div class="source-dot" :class="source.risk"></div><div class="source-info"><b>{{ source.title }}</b><span>{{ source.count }} 个对象 · {{ source.classification }}</span></div><strong>{{ format(source.bytes) }}</strong></div></section>
      <section v-if="scanned" class="result"><h2>下一步建议</h2><div class="suggestion"><b>先观察，再清理</b><span>再次扫描后，Disk Sense 会告诉你哪些空间在持续增长，而不是只显示一次性占用。</span></div></section>
      <section v-if="scanned && events.length" class="result"><h2>最近变化</h2><div v-for="event in events.slice(0,8)" :key="event.path + event.observedAt" class="event"><span class="event-kind">{{ event.kind === 'added' ? '新增' : '变更' }}</span><div><b>{{ event.path }}</b><small>{{ event.observedAt }}</small></div></div></section>
      <section class="result"><div class="result-head"><h2>我的空间记忆</h2><button class="quiet" @click="showMemory=true">添加记忆</button></div><div v-if="memories.length" v-for="memory in memories" :key="memory.id" class="memory"><b>{{ memory.subject }}</b><span>{{ memory.content }}</span></div><p v-else class="muted">还没有记忆。扫描后可以记录目录用途和保留习惯。</p></section>
    </section>
    <div v-if="showAgent" class="modal" @click.self="showAgent=false"><div class="modal-card"><h2>Agent 上下文</h2><p>可提供给其他 Agent 的内容默认只有文件元数据和空间分类，不包含文件内容，也不允许直接修改文件。</p><pre>{{ agentJson }}</pre><button class="scan" @click="copyAgent">复制上下文</button></div></div>
    <div v-if="showMemory" class="modal" @click.self="showMemory=false"><div class="modal-card"><h2>记录空间记忆</h2><input v-model="memorySubject" placeholder="目录或应用名称" /><textarea v-model="memoryContent" placeholder="例如：这是正在使用的项目，不要建议删除"></textarea><button class="scan" @click="saveMemory">保存记忆</button></div></div>
  </main>
</template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { aggregateSources } from '../application/space-service'
import { desktopApi } from '../platform/api'
import CleanerPanel from './CleanerPanel.vue'
import type { SpaceSource } from '../domain/storage'
const view = ref('overview'); const scanning = ref(false); const scanned = ref(false); const sources = ref<SpaceSource[]>([]); const showAgent = ref(false); const showMemory = ref(false); const events = ref<any[]>([]); const memories = ref<any[]>([]); const memorySubject = ref(''); const memoryContent = ref('')
const agentJson = '{\n  "schemaVersion": 1,\n  "permissions": {\n    "readMetadata": true,\n    "readContent": false,\n    "mutateFiles": false\n  }\n}'
function format(n:number){if(n<1024)return `${n} B`;const u=['KB','MB','GB','TB'];let i=-1;do{n/=1024;i++}while(n>=1024&&i<u.length-1);return `${n.toFixed(n>=100?0:n>=10?1:2)} ${u[i]}`}
async function runScan(){scanning.value=true;const api=desktopApi();if(api){const result=await api.scan();sources.value=aggregateSources(result.items);events.value=result.events||[];scanned.value=true;scanning.value=false;return}await new Promise(r=>setTimeout(r,500));const samples=[{id:'1',path:'C:/Users/You/AppData/Local/Chrome/Cache/a',volume:'C:',size:3.2e9,fileCount:1834,classification:'rebuildable-cache' as const,source:'浏览器缓存',risk:'low' as const,confidence:.95,evidence:[{type:'path',value:'Chrome Cache'}],actions:['inspect' as const,'trash' as const]},{id:'2',path:'C:/Users/You/Downloads/old.zip',volume:'C:',size:1.8e9,fileCount:1,classification:'stale' as const,source:'长期未使用内容',risk:'medium' as const,confidence:.71,evidence:[{type:'age',value:'超过 180 天未访问'}],actions:['inspect' as const,'move' as const,'archive' as const]}];sources.value=aggregateSources(samples);scanned.value=true;scanning.value=false}
async function copyAgent(){await navigator.clipboard?.writeText(agentJson)}
async function saveMemory(){const api=desktopApi();const item={subject:memorySubject.value,content:memoryContent.value,tags:[],source:'user',confidence:1};if(api)memories.value=[await (api as any).saveMemory(item),...memories.value];else memories.value=[{...item,id:Date.now()} as any,...memories.value];memorySubject.value='';memoryContent.value='';showMemory.value=false}
onMounted(async()=>{const api=desktopApi();if(api){memories.value=await (api as any).listMemories();(api as any).onChange((change:any)=>{events.value=[{...change,kind:'live-change'},...events.value].slice(0,50)})}})
</script>
