<template><section class="cleaner-panel"><div class="panel-head"><div><p class="kicker">CONVENTIONAL CLEANER</p><h2>常规清理</h2><p>成熟、低风险、可解释的清理项目。所有删除进入回收站。</p></div><button v-if="selected.length" class="scan" @click="execute">确认清理 {{ format(selectedBytes) }}</button></div><div class="cleaner-grid"><article v-for="rule in rules" :key="rule.id" class="clean-rule"><div><span class="rule-cat">{{ rule.category }}</span><h3>{{ rule.title }}</h3><p>{{ rule.reason }}</p></div><div class="rule-result" v-if="results[rule.id]"><b>{{ format(results[rule.id].total) }}</b><small>{{ results[rule.id].files.length }} 个文件</small></div><button class="quiet" @click="scan(rule.id)">{{ results[rule.id] ? '重新扫描' : '扫描' }}</button><label v-if="results[rule.id]?.files.length" class="select-all"><input type="checkbox" :checked="isSelected(rule.id)" @change="toggle(rule.id)">选择此类别</label><div v-if="results[rule.id]?.files.length" class="rule-files"><div v-for="file in results[rule.id].files.slice(0,8)" :key="file.path"><span>{{ file.name }}</span><small>{{ format(file.size) }}</small></div></div></article></div><p v-if="message" class="muted">{{ message }}</p></section></template>
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
const rules=ref<any[]>([]);const results=reactive<Record<string,any>>({});const selected=ref<any[]>([]);const message=ref('')
const selectedBytes=computed(()=>selected.value.reduce((s,x)=>s+x.size,0))
function format(n:number){if(n<1024)return `${n} B`;const u=['KB','MB','GB','TB'];let i=-1;do{n/=1024;i++}while(n>=1024&&i<u.length-1);return `${n.toFixed(n>=100?0:n>=10?1:2)} ${u[i]}`}
async function scan(id:string){const api=(window as any).diskSense;if(api)results[id]=await api.cleanerScan(id);else results[id]={total:0,files:[]}}
function isSelected(id:string){const files=results[id]?.files||[];return files.length>0&&files.every((x:any)=>selected.value.some(y=>y.path===x.path))}
function toggle(id:string){const files=results[id]?.files||[];if(isSelected(id))selected.value=selected.value.filter(x=>!files.some((y:any)=>y.path===x.path));else selected.value=[...selected.value,...files.filter((x:any)=>!selected.value.some(y=>y.path===x.path))]}
async function execute(){if(!selected.value.length)return;if(!confirm(`确认将 ${selected.value.length} 个文件移入回收站？`))return;const api=(window as any).diskSense;const job=await api.cleanerExecute(selected.value);message.value=`已处理 ${job.results.filter((x:any)=>x.success).length} 个文件，释放 ${format(job.freed)}`;selected.value=[];for(const rule of rules.value)if(results[rule.id])await scan(rule.id)}
onMounted(async()=>{const api=(window as any).diskSense;rules.value=api?await api.cleanerRules():[{id:'demo',title:'示例缓存',category:'演示',risk:'low',reason:'仅用于界面预览。'}]})
</script>
